---
title: "Guide for use vus function"
author: "Duc-Khanh To"
date: '`r Sys.Date()`'
vignette: >
  %\VignetteIndexEntry{Guide for use vus and ROC_emp_surface function}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
output: html_document
---

```{r check pandoc, eval=TRUE, echo=FALSE}
if (!requireNamespace("rmarkdown", quietly = TRUE) ||
      !rmarkdown::pandoc_available("1.14")) {
    warning(call. = FALSE, "These vignettes assume rmarkdown and pandoc version 1.14. These were not found. Older versions will not work.")
    knitr::knit_exit()
  }
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
library(emplikDTA)
```

# Simulated data

```{r}
mu_true <- c(0, 2.5, 3.69)
sigma_true <- c(1, 1.1, 1.2)

n1 <- 15
n2 <- 15
n3 <- 15

set.seed(345)
X1 <- rnorm(n1, mu_true[1], sigma_true[1])
X2 <- rnorm(n2, mu_true[2], sigma_true[2])
X3 <- rnorm(n3, mu_true[3], sigma_true[3])
```

## Compute VUS

```{r}
vus(x = X1, y = X2, z = X3)
```

```{r}
data_test <- data.frame(biom = c(X1, X2, X3), 
                        diag = rep(c("1", "2", "3"), c(n1, n2, n3)))
```


```{r}
vus(formula = biom ~ diag, data = data_test)
```


```{r}
vus(formula = biom ~ diag, data = data_test, ci_level = 0.90)
```

```{r}
vus(formula = biom ~ diag, data = data_test, diag_levels = c("1", "2", "3"))
```

```{r}
vus(formula = biom ~ diag, data = data_test, diag_levels = c("2", "3", "1"))
```


```{r}
out_test <- vus(formula = biom ~ diag, data = data_test)
print(out_test)
```

## Plot results of vus

```{r}
vus(formula = biom ~ diag, data = data_test, plot = TRUE)
```

