// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aucC_ties
double aucC_ties(NumericVector x, NumericVector y);
RcppExport SEXP _emplikDTA_aucC_ties(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(aucC_ties(x, y));
    return rcpp_result_gen;
END_RCPP
}
// vusC_ties
double vusC_ties(NumericVector tt1, NumericVector tt2, NumericVector tt3);
RcppExport SEXP _emplikDTA_vusC_ties(SEXP tt1SEXP, SEXP tt2SEXP, SEXP tt3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tt1(tt1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tt2(tt2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tt3(tt3SEXP);
    rcpp_result_gen = Rcpp::wrap(vusC_ties(tt1, tt2, tt3));
    return rcpp_result_gen;
END_RCPP
}
// cdf_kernel_C
NumericVector cdf_kernel_C(NumericVector x, NumericVector X, int Ktype, double bwd);
RcppExport SEXP _emplikDTA_cdf_kernel_C(SEXP xSEXP, SEXP XSEXP, SEXP KtypeSEXP, SEXP bwdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type Ktype(KtypeSEXP);
    Rcpp::traits::input_parameter< double >::type bwd(bwdSEXP);
    rcpp_result_gen = Rcpp::wrap(cdf_kernel_C(x, X, Ktype, bwd));
    return rcpp_result_gen;
END_RCPP
}
// simpson
double simpson(arma::vec fx, int nx, double hx);
RcppExport SEXP _emplikDTA_simpson(SEXP fxSEXP, SEXP nxSEXP, SEXP hxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type fx(fxSEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< double >::type hx(hxSEXP);
    rcpp_result_gen = Rcpp::wrap(simpson(fx, nx, hx));
    return rcpp_result_gen;
END_RCPP
}
// cdf_loocv_kernel_C
double cdf_loocv_kernel_C(NumericVector x, NumericVector X, int Ktype, double bwd, double hx);
RcppExport SEXP _emplikDTA_cdf_loocv_kernel_C(SEXP xSEXP, SEXP XSEXP, SEXP KtypeSEXP, SEXP bwdSEXP, SEXP hxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type Ktype(KtypeSEXP);
    Rcpp::traits::input_parameter< double >::type bwd(bwdSEXP);
    Rcpp::traits::input_parameter< double >::type hx(hxSEXP);
    rcpp_result_gen = Rcpp::wrap(cdf_loocv_kernel_C(x, X, Ktype, bwd, hx));
    return rcpp_result_gen;
END_RCPP
}
// cv_bwd_C
List cv_bwd_C(NumericVector x, NumericVector X, int Ktype, double hx, NumericVector bwd_seq);
RcppExport SEXP _emplikDTA_cv_bwd_C(SEXP xSEXP, SEXP XSEXP, SEXP KtypeSEXP, SEXP hxSEXP, SEXP bwd_seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type Ktype(KtypeSEXP);
    Rcpp::traits::input_parameter< double >::type hx(hxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bwd_seq(bwd_seqSEXP);
    rcpp_result_gen = Rcpp::wrap(cv_bwd_C(x, X, Ktype, hx, bwd_seq));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_emplikDTA_aucC_ties", (DL_FUNC) &_emplikDTA_aucC_ties, 2},
    {"_emplikDTA_vusC_ties", (DL_FUNC) &_emplikDTA_vusC_ties, 3},
    {"_emplikDTA_cdf_kernel_C", (DL_FUNC) &_emplikDTA_cdf_kernel_C, 4},
    {"_emplikDTA_simpson", (DL_FUNC) &_emplikDTA_simpson, 3},
    {"_emplikDTA_cdf_loocv_kernel_C", (DL_FUNC) &_emplikDTA_cdf_loocv_kernel_C, 5},
    {"_emplikDTA_cv_bwd_C", (DL_FUNC) &_emplikDTA_cv_bwd_C, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_emplikDTA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
