# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aucC_ties <- function(x, y) {
    .Call(`_emplikDTA_aucC_ties`, x, y)
}

vusC_ties <- function(tt1, tt2, tt3) {
    .Call(`_emplikDTA_vusC_ties`, tt1, tt2, tt3)
}

